version: "3.8"

services:
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8085:80"
    restart: unless-stopped

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8086:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped